apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-ricospace-settings
spec:
  forms:
    - group: 首页设置
      label: 左侧
      formSchema:
          -  $formkit: 'text'
             name: titleLeft
             label: 标题左侧
             value : ""
          -  $formkit: 'text'
             name: subtitleLeft
             label: 标题右侧
             value : 欢迎来到我的个人博客
          -  $formkit: 'text'
             name: titlebgLeft
             label: 标题背景左侧
             value : ""
          -  $formkit: 'text'
             name: titlebgRight
             label: 标题背景右侧
             value : ""
          -  $formkit: 'text'
             name: descriptionLeft
             label: 描述
             value : 这是一个使用 Rico Space 主题搭建的个人博客网站，分享我的技术文章和生活点滴。 
        - $formkit: array
          name: home_links
          label: 社交链接
          value:
            - value: twitter
            - value: youtube
            - value: bilibili
            - value: github
            - value: telegram
            - value: email
          itemLabels:
            - type: text
              label: $value.value
            - type: text
              label: $value.home_links_url
          children:
            - $formkit: select
              name: value
              label: 类型
              options:
                - label: 首页邮箱
                  value: email
                - label: Twitter
                  value: twitter
                - label: Youtube
                  value: youtube
                - label: 哔哩哔哩
                  value: bilibili
                - label: Github
                  value: github
                - label: Telegram
                  value: telegram

                - label: Gitee
                  value: gitee
                - label: 少数派
                  value: shaoshupai
                - label: 掘金
                  value: juejin
                - label: CSDN
                  value: csdn
                - label: 知乎
                  value: zhihu

                - label: 微博链接
                  value: weibo
                - label: 微信（个人）
                  value: weixin
                - label: 微信公众号
                  value: weixin_mp
                - label: 小红书
                  value: xiaohongshu
                - label: 酷安
                  value: coolapk
                - label: 社区/论坛
                  value: community

                - label: 自定义
                  value: custom
                - $formkit: text
                  name: home_links_url
                  label: 链接
                - $formkit: attachment
                  if: '$value.value === "custom"'
                  name: custom_icon
                  label: 自定义图标
                  help: "请选择图标，推荐使用SVG格式图标。"
    - group: 首页设置
      label: 右侧
      formSchema:
          -  $formkit: 'text'
             name: titleRight
             label: 首页右侧图地址
             value : ""


