apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: rico-space
spec:
  displayName: Rico Space
  author:
    name: Rico
  description: 一个太空风格的个人博客主题
  homepage: https://github.com/yourusername/rico-space
  logo: "https://free.picui.cn/free/2026/01/05/695b6f50452b4.png"
  repo: ""
  settingName: "theme-ricospace-setting"
  configMapName: "theme-ricospace-setting-configMap"
  version: 1.0.0
  require: ">=2.10.0"
  customTemplates:
    page:
      - name: article
        description: 文章列表页
        screenshot: ""
        file: archives.html
      - name: moments
        description: 动态页
        screenshot: ""
        file: moments.html
      - name: photos
        description: 图册页
        screenshot: ""
        file: photos.html
      - name: projects
        description: 项目页
        screenshot: ""
        file: page.html
